# Generated by Django 4.2.6 on 2023-12-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="number_of_faculty",
            field=models.TextField(default=1, verbose_name="Номер факультета"),
            preserve_default=False,
        ),
    ]
